name: Remote Prechecks Workflow Bash2

on:
  push:
    branches:
      - Ubuntu

jobs:
  run-prechecks:
    runs-on: self-hosted

    environment: vm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Prechecks on Remote Machine
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user1@192.168.1.105 <<EOF
          echo "Running commands on remote machine:"
          whoami
          ip a
          # Navigate to the home directory or a specific folder
          cd /home/user1
          # Clone the GitHub repository
          git clone https://github.com/Pranav5Murali/Practice.git || echo "Repository already exists"
          EOF
