name: Logs cleanup


on:
  push:
    branches:
      - Ubuntu

jobs:
  run-prechecks:
    runs-on: self-hosted
    environment: vm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH Connection - Verify User and System Info
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user1@192.168.1.105 <<EOF
          echo "Running commands on remote machine:"
          whoami
          ip a
          EOF

      - name: SSH Connection - Clone GitHub Repository1a
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user1@192.168.1.105 <<EOF
          cd /home/user1
          if [ -d "Practice" ]; then
            echo "Repository already exists. Skipping clone."
          else
            git clone https://github.com/Pranav5Murali/Practice.git
            echo "The status of git clone command is"
            echo $?
          fi
          EOF

      - name: SSH Connection - Execute the workflow to delete the log files
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: |
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user1@192.168.1.105 <<EOF
            cd /home/user1/Practice
            # Escape $() with \ to prevent local expansion and ensure the find command runs on the remote machine
            job=\$(find . -type f -name "delete_logs.sh" | head -n 1)
            echo $?
            echo "Executing chmod command"
            chmod +x "\$job"
            echo $?
            echo "Executing the bash script now"
            bash "\$job"
            echo $?
            EOF
