name: Remote Prechecks Workflow Bash2

on:
  push:
    branches:
      - Ubuntu

jobs:
  run-prechecks:
    runs-on: self-hosted

    environment: vm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH Connection - Verify User and System Info
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user1@192.168.1.105 <<EOF
          echo "Running commands on remote machine:"
          whoami
          ip a
          EOF

      - name: SSH Connection - Navigate to Home Directory
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user1@192.168.1.105 <<EOF
          cd /home/user1
          pwd
          echo "Navigated to home directory."
          EOF

      - name: SSH Connection - Clone GitHub Repository
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user1@192.168.1.105 <<EOF
          cd /home/user1
          if [ -d "Practice" ]; then
            echo "Repository already exists. Skipping clone."
          else
            if git clone https://github.com/Pranav5Murali/Practice.git; then
              echo "Repository cloned successfully."
            else
              echo "Failed to clone repository. Please check the URL or network connectivity."
            fi
          fi
          EOF
